

services:
  dashboard-app:
    build: .
    ports:
      - "5174:5174"
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    volumes:
      - .:/app
      - /app/node_modules
